[package]
name = "barker"
version = "0.1.0"
edition = "2021"

[dependencies]
rusqlite = { version = "0.27.0", features = ["bundled"] }
afire = { version = "1.0.0", features = ["tracing"] }
parking_lot = "0.12.0"
serde_json = "1.0.79"
rand = "0.8.5"
sha2 = "0.10.2"
simple_config_parser = "1.0.0"
